### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#1]
Dear Danilo,

I am deeply impressed on this new project and am following it since a week.
Would you please like to consider some fundamental changes from me?
After some refactoring my state of your git check-ins at 2021-09-09 is in

 http://www.ch-werner.de/tcl-opencv.tgz

Among the changes are:

* no mutex required when OpenCV guarantees it
* organize things to be aware of Tcl threading, i.e.in ClientData, not in static variables
* make it more Tcl thread safe to allow for using Tcl threads
* add destructors and callbacks for command deletion to perform object cleanup
* start to add some introspection stuff like cv::_info and partially the _name, _proc, and _type methods

Hope, that you find some good ideas and take them over.
Glad were I, if you would have a talk on this year's SQLite+Tcl conference regarding tcl-opencv.

All the best,
Christian

**Comment by undroidwish** [comment]
Dear Danilo,

I've updated the URL above to your current (2021-09-12) git master branch with some changes:

* some minor fixes in using the Opencv_Data.cmd_* struct fields
* some minor changes regarding formatting
* some ifdefs to deal with OpenCV version 3.x (I'm using Debian 10 which has not OpenCV 4.x)
* the configure (i.e. build-time) option --enable-tkphoto to allow for optional Tk support in the cv::Mat class (toPhoto method) and a cv::fromPhoto function to make a cv::Mat from a Tk photo image. If enabled it may be necessary to provide a --with-tk configure option, too, but this depends on the development environment.

Again, thanks for your work
Christian

**Comment by ray2501** [comment]
Thanks for your effort.
