### ISSUE TITLE
Some fixes and cosmetic reformatting

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#10]
Dear Danilo,

please find attached another patch with an important fix regarding CV_Error(). Caution, this must not be called outside a try/catch block since it throws a cv::Exception, which isn't catched. Instead, Opencv_SetResult() should be used. Other things are a little bit cosmetic regarding formatting.

BR,
Christian

[tcl-opencv-20210930-2.diff.gz](https://github.com/ray2501/tcl-opencv/files/7261310/tcl-opencv-20210930-2.diff.gz)

**Comment by ray2501** [comment]
OK.
