### ISSUE TITLE
OpenCV 4.x+ requires enabled C++11 support

### ISSUE THREAD

**Issue by nico-robert** [ray2501/tcl-opencv#11]
Hi @ray2501 ,

- OS : `Mac Big Sur`
- Version : `Apple clang version 12.0.0 (clang-1200.0.31.1)`
- Target :` x86_64-apple-darwin20.6.0`
- OpenCV version : `4.5.3`

**error**: "OpenCV 4.x+ requires enabled C++11 support"

I added this flag `-std=c++11` in the Makefile to make it work.
It’s a mistake on my part...

Regards

Nicolas

**Comment by ray2501** [comment]
I add the flag -std=c++11 in configure.ac and generate the new files. It should OK now.

**Comment by ray2501** [comment]
It should OK now. If this issue still exists, please re-open or create a new issue for me.

**Comment by nico-robert** [comment]
thanks , it works.
Regards
Nicolas
