### ISSUE TITLE
to/from bytearray methods plus refactoring

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#13]
Dear Danilo,

please find attached a patch against version 0.10 which adds methods similar to the photo stuff but working with Tcl byte arrays (plus some meta info like width, height and bytes per pixel/channel). FileStorage support for the AffineFeature class is added. All assembled Tcl lists with constant size are build using Tcl_NewListObj() with a Tcl_Obj pointer array instead of calls to Tcl_ListObjAppendElement() with the benefit of lesser code to write and most likely faster execution.

BR,
Christian

[tcl-opencv-0.10.diff.gz](https://github.com/ray2501/tcl-opencv/files/7306777/tcl-opencv-0.10.diff.gz)

**Comment by ray2501** [comment]
Thank you.
