### ISSUE TITLE
Callbacks again

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#18]
Dear Danilo,

the following patch deals with the situation when callbacks are overwritten, i.e. multiple consecutive calls of `cv::setMouseCallback` and `cv::createTrackbar` are carried out. And two test cases are added.

BR
Christian

[tcl-opencv-20211028.diff.gz](https://github.com/ray2501/tcl-opencv/files/7445917/tcl-opencv-20211028.diff.gz)

**Comment by ray2501** [comment]
Thank you.
