### ISSUE TITLE
Refectoring, again

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#2]
Dear Danilo,

I've updated the URL http://www.ch-werner.de/tcl-opencv.tgz to your current (2021-09-12) git master branch with some changes:

* some minor fixes in using the Opencv_Data.cmd_* struct fields
* some minor changes regarding formatting
* some ifdefs to deal with OpenCV version 3.x (I'm using Debian 10 which has not OpenCV 4.x)
* the configure (i.e. build-time) option --enable-tkphoto to allow for optional Tk support in the cv::Mat class (toPhoto method) and a cv::fromPhoto function to make a cv::Mat from a Tk photo image. If enabled it may be necessary to provide a --with-tk configure option, too, but this depends on the development environment.

Again, thanks for your work
Christian

**Comment by ray2501** [comment]
Thanks for your effort.
