### ISSUE TITLE
imdecode/imencode plus some refactoring

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#3]
Dear Danilo,

this time I've attached a patch against the 0.8 release which adds cv::imdecode and cv::imencode to transfer data between cv::Mat and Tcl byte arrays. The strings for e.g. filenames are now recoded to system encoding or UTF-8 normalized for putText. A few fixes and a little bit code cleanup is also in the patch.

Hope, you'll find it useful,
Christian

[tcl-opencv-0.8.diff.gz](https://github.com/ray2501/tcl-opencv/files/7160789/tcl-opencv-0.8.diff.gz)

**Comment by ray2501** [comment]
Thanks for your effort.
