### ISSUE TITLE
FileStorage interface etc.

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#4]
Dear Danilo,

please find attached a new tfstorage.cpp module which interfaces cv::FileStorage. It's not perfect but a starting point. Most of it even works with OpenCV 3.2 on Debian 10. Other minor changes are the methods _command, _name, and _type for the various singleton objects in order to have symmetry with the other stuff.

Hope, you find it useful,
Christian

[tcl-opencv-20210919.diff.gz](https://github.com/ray2501/tcl-opencv/files/7192368/tcl-opencv-20210919.diff.gz)

**Comment by ray2501** [comment]
Thanks for your effort.
