### ISSUE TITLE
More on FileStorage interface etc.

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#5]
Dear Danilo,

please find a patch attached to add the readObj and writeObj methods to cv::FileStorage. Now it is more general
and allows to (de)serialize most of the supported objects/types. Some small other cosmetic changes are included, too.

All the best,
Christian

[tcl-opencv-20210923.diff.gz](https://github.com/ray2501/tcl-opencv/files/7220868/tcl-opencv-20210923.diff.gz)

**Comment by ray2501** [comment]
Thanks for your effort.
