### ISSUE TITLE
FileStorage again

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#6]
Dear Danilo,

the (de)serialization of cv::ml::TrainData was buggy, please find the fix in the attachment. A test case for it is added, too.

BR,
Christian

[tcl-opencv-20210924.diff.gz](https://github.com/ray2501/tcl-opencv/files/7224751/tcl-opencv-20210924.diff.gz)

**Comment by ray2501** [comment]
Thanks for your effort.
