### ISSUE TITLE
Refactoring: Error/exception handling

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-opencv#9]
Dear Danilo,

please find a patch attached which refactors error handling and exception reporting with respect to support Tcl's own try/catch construct. It all goes now through two central functions which makes things easier to change, should later a redesign be needed.

This time it is a very large patch, so please take your time for review.

Other minor things are attemptckalloc() at some places instead of ckalloc() to detect out of memory conditions.

Again, I hope that it's useful,
Christian

[tcl-opencv-20210929.diff.gz](https://github.com/ray2501/tcl-opencv/files/7254360/tcl-opencv-20210929.diff.gz)

**Comment by undroidwish** [comment]
Dear Danilo,

here's a small addendum with some error strings and codes fixed plus serialization for cv::TermCriteria added.

BR,
Christian

[tcl-opencv-20210930.diff.gz](https://github.com/ray2501/tcl-opencv/files/7257354/tcl-opencv-20210930.diff.gz)

**Comment by ray2501** [comment]
Thank you.
